version: "3.8"
services:
  mysql:
    image: "mysql:8.0"
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: webflux
      MYSQL_ROOT_PASSWORD: 1234
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
  mongodb:
    image: "mongo:latest"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=reactive
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=mydb